### ISSUE TITLE
Suggestion - no need to use font-weight:bold on headings

### ISSUE THREAD

**Issue by jzhu01** [sappla/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/sappla/prj-rev-bwfs-dasmoto/blob/1301aaf1e1374426b59a80cee123c01e69c483c1/DasmotoArtsCrafts/resources/css/style.css#L12

Since headings are actually bolded by default here, we don't need to specify it.

**Comment by sappla** [comment]
Thanks for the suggestion. I haven't thought about it!
